const categories={work:{label:'업무',class:'work'},journal:{label:'일기',class:'journal'},emotion:{label:'감정',class:'emotion'},todo:{label:'할 일',class:'todo'},idea:{label:'아이디어',class:'idea'},other:{label:'기타',class:'other'}};
const today='2024-06-17';
const seed=[{id:1,date:today,time:'09:12',text:'오전 팀 싱크에서 신규 캠페인 방향 정리하기',category:'work'},{id:2,date:today,time:'11:30',text:'점심으로 먹은 냉면이 생각보다 맛있었다.',category:'journal'},{id:3,date:today,time:'13:05',text:'오후에는 조금 집중이 잘 안 되는 날. 커피 한 잔 해야겠다.',category:'emotion'},{id:4,date:today,time:'14:20',text:'이번 주 금요일까지 제안서 1차 초안 완성하기',category:'todo',done:false},{id:5,date:today,time:'16:48',text:'사용자 기록을 감정 온도 그래프로 보여주면 어떨까?',category:'idea'},{id:6,date:'2024-06-16',time:'10:20',text:'독서 모임에서 나눌 책의 인상 깊은 문장 표시하기',category:'todo',done:true},{id:7,date:'2024-06-16',time:'18:40',text:'오랜만에 친구를 만나서 마음이 편안해졌다.',category:'emotion'}];
let entries=JSON.parse(localStorage.getItem('memento-entries')||'null')||seed;let view='today',selectedDate=today,activeCategory='all',query='',todoRange='all';
const $=s=>document.querySelector(s);const save=()=>localStorage.setItem('memento-entries',JSON.stringify(entries));
function autoCategory(text){if(/해야|하기|제출|완료|확인|보내|정리/.test(text))return'todo';if(/회의|업무|프로젝트|캠페인|고객|제안서/.test(text))return'work';if(/느낌|기분|행복|불안|힘들|편안|감정|집중/.test(text))return'emotion';if(/아이디어|어떨까|생각/.test(text))return'idea';if(/오늘|점심|아침|저녁|하루/.test(text))return'journal';return'other'}
function formatDate(date){const d=new Date(date+'T00:00:00');return d.toLocaleDateString('ko-KR',{month:'long',day:'numeric',weekday:'short'}).replace('요일','')}
function filtered(list=entries){return list.filter(e=>(activeCategory==='all'||e.category===activeCategory)&&(!query||e.text.toLowerCase().includes(query.toLowerCase())))}
function tag(c){return `<span class="tag ${categories[c].class}">${categories[c].label}</span>`}
function entryCard(e){return `<article class="entry"><div class="entry-meta">${tag(e.category)}<span class="time">${e.time}</span></div><p class="entry-text">${escapeHtml(e.text)}</p><div class="entry-bottom"><span class="time">${formatDate(e.date)}</span><div class="entry-actions"><button data-edit="${e.id}" aria-label="카테고리 수정">카테고리 수정</button>${e.category==='todo'?`<button data-toggle="${e.id}">${e.done?'완료됨':'완료 처리'}</button>`:''}</div></div></article>`}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const title=view==='today'?'오늘의 기록':view==='calendar'?'날짜별 보기':'할 일 모아보기';$('#page-title').textContent=title;document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='today')renderToday();if(view==='calendar')renderCalendar();if(view==='todos')renderTodos();bindActions()}
function renderToday(){const list=filtered(entries.filter(e=>e.date===selectedDate)).sort((a,b)=>a.time.localeCompare(b.time));const dayCount=entries.filter(e=>e.date===selectedDate).length;const cats=Object.keys(categories).map(c=>[c,entries.filter(e=>e.date===selectedDate&&e.category===c).length]).filter(x=>x[1]);$('#app-view').innerHTML=`<div class="summary-card"><div><h3>${formatDate(selectedDate)} 기록 요약</h3><p>${dayCount?`오늘은 ${dayCount}개의 기록을 남겼어요. ${cats.map(x=>`${categories[x[0]].label} ${x[1]}개`).join(', ')}.`:'아직 남겨진 기록이 없어요. 첫 기록을 남겨보세요.'}</p></div><div class="summary-stats"><div class="summary-stat"><strong>${dayCount}</strong><span>전체 기록</span></div><div class="summary-stat"><strong>${entries.filter(e=>e.date===selectedDate&&e.category==='todo').length}</strong><span>할 일</span></div></div></div><div class="section-head"><div><h2>오늘의 타임라인</h2><p>작성한 순서대로 차곡차곡</p></div><div class="date-switcher"><button data-date="prev">‹</button><span>${formatDate(selectedDate)}</span><button data-date="next">›</button></div></div><div class="filter-row">${[['all','전체'],...Object.entries(categories).map(([k,v])=>[k,v.label])].map(([k,l])=>`<button class="filter ${activeCategory===k?'active':''}" data-filter="${k}">${l}</button>`).join('')}</div><div class="entry-list">${list.length?list.map(entryCard).join(''):'<div class="empty">이 조건에 맞는 기록이 없어요.</div>'}</div>`}
function renderCalendar(){let days=[];for(let i=1;i<=30;i++){const date=`2024-06-${String(i).padStart(2,'0')}`, has=entries.filter(e=>e.date===date);days.push(`<button class="day ${date===selectedDate?'selected':''}" data-select-date="${date}">${i}${has.length?`<span class="dots">${has.slice(0,3).map(()=>'<i></i>').join('')}</span>`:''}</button>`)}$('#app-view').innerHTML=`<div class="section-head"><div><h2>기록 달력</h2><p>날짜를 누르면 그날의 타임라인으로 이동해요.</p></div><div class="date-switcher"><span>2024년 6월</span></div></div><div class="calendar-card"><div class="calendar-grid"><b>일</b><b>월</b><b>화</b><b>수</b><b>목</b><b>금</b><b>토</b><span></span><span></span><span></span><span></span><span></span><span></span>${days.join('')}</div></div>`}
function renderTodos(){let list=filtered(entries.filter(e=>e.category==='todo'));if(todoRange==='open')list=list.filter(e=>!e.done);if(todoRange==='week'){const end=new Date(today+'T00:00:00'),start=new Date(end);start.setDate(end.getDate()-6);list=list.filter(e=>{const d=new Date(e.date+'T00:00:00');return d>=start&&d<=end})}const groups=[...new Set(list.map(e=>e.date))].sort().reverse();$('#app-view').innerHTML=`<div class="section-head"><div><h2>할 일 모아보기</h2><p>날짜 범위와 검색어로 필요한 할 일만 찾아보세요.</p></div></div><div class="filter-row"><button class="filter ${todoRange==='all'?'active':''}" data-todo-range="all">전체 기간</button><button class="filter ${todoRange==='week'?'active':''}" data-todo-range="week">최근 7일</button><button class="filter ${todoRange==='open'?'active':''}" data-todo-range="open">미완료만</button></div><div class="todo-layout">${groups.length?groups.map(d=>`<section class="todo-day"><h3>${formatDate(d)}</h3>${list.filter(e=>e.date===d).map(e=>`<div class="todo-row ${e.done?'done':''}"><button class="check ${e.done?'done':''}" data-toggle="${e.id}">${e.done?'✓':''}</button><span>${escapeHtml(e.text)}</span></div>`).join('')}</section>`).join(''):'<div class="empty">조건에 맞는 할 일이 없어요.</div>'}</div>`}
function bindActions(){$('[data-filter]')?.parentElement?.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){activeCategory=b.dataset.filter;render()}});$('[data-date="prev"]')?.addEventListener('click',()=>moveDate(-1));$('[data-date="next"]')?.addEventListener('click',()=>moveDate(1));document.querySelectorAll('[data-select-date]').forEach(b=>b.addEventListener('click',()=>{selectedDate=b.dataset.selectDate;view='today';render()}));document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>{const x=entries.find(e=>e.id==b.dataset.toggle);x.done=!x.done;save();render()}));document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>{const x=entries.find(e=>e.id==b.dataset.edit), next=prompt('카테고리를 입력하세요: 업무 / 일기 / 감정 / 할 일 / 아이디어 / 기타',categories[x.category].label);const map={'업무':'work','일기':'journal','감정':'emotion','할 일':'todo','아이디어':'idea','기타':'other'};if(map[next]){x.category=map[next];save();render();showToast('카테고리를 수정했어요.')}}));document.querySelectorAll('[data-todo-range]').forEach(b=>b.addEventListener('click',()=>{todoRange=b.dataset.todoRange;render()}))}
function moveDate(delta){const d=new Date(selectedDate+'T00:00:00');d.setDate(d.getDate()+delta);selectedDate=d.toISOString().slice(0,10);render()}
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;activeCategory='all';render()}));$('#add-entry').addEventListener('click',addEntry);$('#entry-input').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();addEntry()}});function addEntry(){const input=$('#entry-input'),text=input.value.trim();if(!text){showToast('내용을 먼저 입력해 주세요.');return}const now=new Date(),time=now.toTimeString().slice(0,5),cat=$('#category-select').value==='auto'?autoCategory(text):$('#category-select').value;entries.push({id:Date.now(),date:today,time,text,category:cat,done:false});save();input.value='';$('#category-select').value='auto';selectedDate=today;view='today';render();showToast('기록을 남겼어요.')}
$('#search-toggle').addEventListener('click',()=>{$('#search-bar').classList.toggle('hidden');$('#search-input').focus()});$('#search-input').addEventListener('input',e=>{query=e.target.value;render()});$('#clear-search').addEventListener('click',()=>{$('#search-input').value='';query='';render()});render();
