"use client";

import { useEffect, useMemo, useState } from "react";
import type { Session, SupabaseClient } from "@supabase/supabase-js";
import { CalendarDays, Check, ChevronLeft, ChevronRight, ClipboardList, Mail, Pencil, Search, Settings, Sparkles, X } from "lucide-react";
import { getSupabaseBrowserClient, supabaseConfigured } from "../lib/supabase";

type Category = "work" | "journal" | "emotion" | "todo" | "idea" | "other";
type View = "today" | "calendar" | "todos";
type Entry = { id: string | number; date: string; time: string; text: string; category: Category; done?: boolean };

const categories: Record<Category, { label: string; color: string; dot: string }> = {
  work: { label: "업무", color: "bg-[#eeeafd] text-[#6e5ac4]", dot: "bg-[#8d7be4]" },
  journal: { label: "일기", color: "bg-[#e6f3f5] text-[#4c91aa]", dot: "bg-[#7da9df]" },
  emotion: { label: "감정", color: "bg-[#fff0ec] text-[#d46e58]", dot: "bg-[#ef754f]" },
  todo: { label: "할 일", color: "bg-[#fff5db] text-[#ae7c20]", dot: "bg-[#f6c85f]" },
  idea: { label: "아이디어", color: "bg-[#e7f5ec] text-[#4c9c72]", dot: "bg-[#75b79a]" },
  other: { label: "기타", color: "bg-[#f0efec] text-[#777]", dot: "bg-[#aaa]" }
};
const demoDate = "2024-06-17";
const demoEntries: Entry[] = [
  { id: "demo-1", date: demoDate, time: "09:12", text: "오전 팀 싱크에서 신규 캠페인 방향 정리하기", category: "work" },
  { id: "demo-2", date: demoDate, time: "11:30", text: "점심으로 먹은 냉면이 생각보다 맛있었다.", category: "journal" },
  { id: "demo-3", date: demoDate, time: "13:05", text: "오후에는 조금 집중이 잘 안 되는 날. 커피 한 잔 해야겠다.", category: "emotion" },
  { id: "demo-4", date: demoDate, time: "14:20", text: "이번 주 금요일까지 제안서 1차 초안 완성하기", category: "todo", done: false },
  { id: "demo-5", date: demoDate, time: "16:48", text: "사용자 기록을 감정 온도 그래프로 보여주면 어떨까?", category: "idea" },
  { id: "demo-6", date: "2024-06-16", time: "10:20", text: "독서 모임에서 나눌 책의 인상 깊은 문장 표시하기", category: "todo", done: true },
  { id: "demo-7", date: "2024-06-16", time: "18:40", text: "오랜만에 친구를 만나서 마음이 편안해졌다.", category: "emotion" }
];

function formatDate(date: string) { return new Intl.DateTimeFormat("ko-KR", { month: "long", day: "numeric", weekday: "short" }).format(new Date(`${date}T00:00:00`)).replace("요일", ""); }
function escapeText(text: string) { return text; }
function autoCategory(text: string): Category { if (/해야|하기|제출|완료|확인|보내|정리/.test(text)) return "todo"; if (/회의|업무|프로젝트|캠페인|고객|제안서/.test(text)) return "work"; if (/느낌|기분|행복|불안|힘들|편안|감정|집중/.test(text)) return "emotion"; if (/아이디어|어떨까|생각/.test(text)) return "idea"; if (/오늘|점심|아침|저녁|하루/.test(text)) return "journal"; return "other"; }
type EntryRow = { id: string; entry_date: string; entry_time: string; text: string; category: Category; done: boolean };
function fromRow(row: EntryRow): Entry { return { id: row.id, date: row.entry_date, time: row.entry_time.slice(0, 5), text: row.text, category: row.category, done: row.done }; }
const supabase = getSupabaseBrowserClient();

export default function Home() {
  const [entries, setEntries] = useState<Entry[]>(demoEntries);
  const [session, setSession] = useState<Session | null>(null);
  const [authLoading, setAuthLoading] = useState(supabaseConfigured);
  const [view, setView] = useState<View>("today");
  const [selectedDate, setSelectedDate] = useState(demoDate);
  const [category, setCategory] = useState<"all" | Category>("all");
  const [query, setQuery] = useState("");
  const [searchOpen, setSearchOpen] = useState(false);
  const [text, setText] = useState("");
  const [inputCategory, setInputCategory] = useState<"auto" | Category>("auto");
  const [todoRange, setTodoRange] = useState<"all" | "week" | "open">("all");
  const [toast, setToast] = useState("");

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(""), 2200); };
  const loadEntries = async (userId: string) => { if (!supabase) return; const { data, error } = await supabase.from("entries").select("id, entry_date, entry_time, text, category, done").eq("user_id", userId).order("entry_date", { ascending: false }).order("entry_time", { ascending: false }); if (error) return notify("기록을 불러오지 못했어요."); const loaded = (data ?? []).map(fromRow); setEntries(loaded); if (loaded[0]) setSelectedDate(loaded[0].date); };
  useEffect(() => {
    if (!supabase) { const saved = window.localStorage.getItem("memento-entries"); if (saved) setEntries(JSON.parse(saved)); return; }
    let mounted = true;
    supabase.auth.getSession().then(({ data: { session: nextSession } }) => { if (!mounted) return; setSession(nextSession); setAuthLoading(false); if (nextSession) loadEntries(nextSession.user.id); });
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, nextSession) => { setSession(nextSession); setAuthLoading(false); if (nextSession) loadEntries(nextSession.user.id); else setEntries([]); });
    return () => { mounted = false; subscription.unsubscribe(); };
  }, []);
  useEffect(() => { if (!supabase) window.localStorage.setItem("memento-entries", JSON.stringify(entries)); }, [entries]);
  const toggleTodo = async (id: Entry["id"]) => { const item = entries.find(entry => entry.id === id); if (!item) return; const nextDone = !item.done; setEntries(items => items.map(entry => entry.id === id ? { ...entry, done: nextDone } : entry)); if (supabase && session && typeof id === "string") { const { error } = await supabase.from("entries").update({ done: nextDone }).eq("id", id).eq("user_id", session.user.id); if (error) notify("완료 상태를 저장하지 못했어요."); } };
  const changeCategory = async (id: Entry["id"], next: Category) => { setEntries(items => items.map(item => item.id === id ? { ...item, category: next } : item)); if (supabase && session && typeof id === "string") { const { error } = await supabase.from("entries").update({ category: next }).eq("id", id).eq("user_id", session.user.id); if (error) notify("카테고리를 저장하지 못했어요."); } };
  const addEntry = async () => { const clean = text.trim(); if (!clean) return notify("내용을 먼저 입력해 주세요."); const now = new Date(); const date = now.toISOString().slice(0, 10); const time = now.toTimeString().slice(0, 5); const nextCategory = inputCategory === "auto" ? autoCategory(clean) : inputCategory; if (supabase && session) { const { data, error } = await supabase.from("entries").insert({ user_id: session.user.id, entry_date: date, entry_time: time, text: clean, category: nextCategory, done: false }).select("id, entry_date, entry_time, text, category, done").single(); if (error || !data) return notify("기록을 저장하지 못했어요."); setEntries(items => [...items, fromRow(data)]); setSelectedDate(date); } else { setEntries(items => [...items, { id: Date.now(), date: demoDate, time, text: clean, category: nextCategory, done: false }]); } setText(""); setInputCategory("auto"); notify("기록을 남겼어요."); };
  const changeDate = (amount: number) => { const date = new Date(`${selectedDate}T00:00:00`); date.setDate(date.getDate() + amount); setSelectedDate(date.toISOString().slice(0, 10)); };
  const filtered = useMemo(() => entries.filter(item => (!query || item.text.toLowerCase().includes(query.toLowerCase())) && (category === "all" || item.category === category)), [entries, query, category]);
  const todos = useMemo(() => { let list = filtered.filter(item => item.category === "todo"); if (todoRange === "open") list = list.filter(item => !item.done); if (todoRange === "week") { const cutoffDate = new Date(); cutoffDate.setDate(cutoffDate.getDate() - 6); const cutoff = cutoffDate.toISOString().slice(0, 10); list = list.filter(item => item.date >= cutoff); } return list; }, [filtered, todoRange]);

  if (authLoading) return <AuthLoading />;
  if (supabaseConfigured && !session && supabase) return <AuthPanel client={supabase} />;

  return <div className="min-h-screen md:flex">
    <aside className="hidden w-[238px] shrink-0 border-r border-[#e9e7e1] px-5 py-8 md:flex md:flex-col">
      <div className="mb-14 ml-3 flex items-center gap-2 font-bold tracking-tight"><Sparkles className="h-6 w-6 text-[#ef754f]" /> <span className="text-xl">memento</span></div>
      <Navigation view={view} onChange={setView} />
      <div className="mt-auto"><div className="mb-5 flex gap-2 rounded-xl bg-[#f1ece6] p-4 text-[11px] leading-7 text-[#8e847a]"><Sparkles className="mt-1 h-4 w-4 shrink-0 text-[#ef754f]" /><p className="m-0">생각을 남겨두면<br /><strong className="text-[#5c554e]">내일의 나</strong>가 고마워요.</p></div><button className="ml-3 flex items-center gap-2 text-sm text-[#92908b]"><Settings className="h-4 w-4" /> 설정</button></div>
    </aside>
    <main className="w-full max-w-[1030px] px-[18px] pb-20 pt-7 sm:px-8 md:px-[68px] md:pt-14">
      <div className="mb-6 flex items-start justify-between md:mb-8"><div><p className="mb-2 text-[10px] font-semibold tracking-[1.6px] text-[#aaa8a2]">{new Intl.DateTimeFormat("en-US", { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(new Date()).toUpperCase()}</p><h1 className="m-0 text-[26px] font-bold tracking-tight md:text-3xl">{view === "today" ? "오늘의 기록" : view === "calendar" ? "날짜별 보기" : "할 일 모아보기"}</h1></div><div className="flex items-center gap-3"><button onClick={() => setSearchOpen(open => !open)} className="p-1 text-[#787672]" aria-label="검색"><Search /></button><button onClick={() => supabase?.auth.signOut()} className="grid h-8 w-8 place-items-center rounded-full bg-[#262625] text-xs font-semibold text-white">M</button></div></div>
      <div className="mb-8 rounded-[14px] border border-[#e9e7e1] bg-white p-4 shadow-[0_7px_25px_rgba(62,47,32,0.06)] md:p-5"><div className="flex gap-3"><Pencil className="mt-1 h-5 w-5 shrink-0 text-[#ef754f]" /><textarea value={text} onChange={event => setText(event.target.value)} onKeyDown={event => { if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); addEntry(); } }} rows={1} placeholder="지금 떠오르는 생각을 자유롭게 적어보세요..." className="min-h-8 w-full resize-none border-0 bg-transparent text-sm outline-none placeholder:text-[#aaa8a2]" /></div><div className="mt-3 flex items-end justify-between gap-2"><span className="hidden text-[11px] text-[#b2b0aa] sm:block">Enter로 빠르게 기록하기</span><div className="ml-auto flex items-center gap-2"><select value={inputCategory} onChange={event => setInputCategory(event.target.value as "auto" | Category)} className="max-w-[86px] bg-transparent text-xs text-[#88857e] outline-none"><option value="auto">자동 분류</option>{Object.entries(categories).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><button onClick={addEntry} className="rounded-lg bg-[#ef754f] px-3 py-2 text-xs font-bold text-white">기록 남기기 <span className="ml-2">↗</span></button></div></div></div>
      {searchOpen && <div className="mb-7 flex items-center gap-3 border-b border-[#e9e7e1] pb-3 text-[#aaa]"><Search className="h-4 w-4" /><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="기록과 할 일을 검색해보세요" className="w-full bg-transparent text-sm outline-none" /><button onClick={() => { setQuery(""); setSearchOpen(false); }}><X className="h-4 w-4" /></button></div>}
      {view === "today" && <TodayView entries={entries} selectedDate={selectedDate} filtered={filtered} category={category} setCategory={setCategory} changeDate={changeDate} toggleTodo={toggleTodo} changeCategory={changeCategory} notify={notify} />}
      {view === "calendar" && <CalendarView entries={entries} selectedDate={selectedDate} onSelect={date => { setSelectedDate(date); setView("today"); }} />}
      {view === "todos" && <TodosView todos={todos} range={todoRange} setRange={setTodoRange} toggleTodo={toggleTodo} />}
    </main>
    <div className="fixed bottom-6 left-1/2 z-10 -translate-x-1/2 rounded-lg bg-[#292927] px-4 py-3 text-xs text-white shadow-xl transition-opacity" style={{ opacity: toast ? 1 : 0, pointerEvents: "none" }}>{toast}</div>
  </div>;
}

function AuthLoading() { return <div className="grid min-h-screen place-items-center bg-[#f8f7f3] text-sm text-[#92908a]">memento를 준비하고 있어요...</div>; }

function AuthPanel({ client }: { client: SupabaseClient }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"login" | "signup">("login"); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setLoading(true); setMessage(""); const result = mode === "login" ? await client.auth.signInWithPassword({ email, password }) : await client.auth.signUp({ email, password, options: { emailRedirectTo: window.location.origin } }); setLoading(false); if (result.error) setMessage(result.error.message); else setMessage(mode === "login" ? "로그인됐어요." : "가입 확인 메일을 확인해 주세요."); };
  return <main className="grid min-h-screen place-items-center bg-[#f8f7f3] px-5 py-12"><section className="w-full max-w-sm rounded-2xl border border-[#e9e7e1] bg-white p-7 shadow-[0_10px_35px_rgba(62,47,32,0.07)]"><div className="mb-8 text-center"><Sparkles className="mx-auto mb-3 h-7 w-7 text-[#ef754f]" /><h1 className="m-0 text-2xl font-bold tracking-tight">memento</h1><p className="mt-2 text-xs text-[#92908a]">어디서든 나의 기록을 이어가세요.</p></div><form onSubmit={submit} className="space-y-3"><label className="block text-xs font-semibold text-[#66635d]">이메일<input type="email" required value={email} onChange={event => setEmail(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#e5e1da] px-3 py-2.5 text-sm outline-none focus:border-[#ef754f]" placeholder="you@example.com" /></label><label className="block text-xs font-semibold text-[#66635d]">비밀번호<input type="password" required minLength={6} value={password} onChange={event => setPassword(event.target.value)} className="mt-1.5 w-full rounded-lg border border-[#e5e1da] px-3 py-2.5 text-sm outline-none focus:border-[#ef754f]" placeholder="6자 이상 입력" /></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-lg bg-[#ef754f] py-3 text-sm font-bold text-white disabled:opacity-50"><Mail className="h-4 w-4" />{loading ? "처리 중..." : mode === "login" ? "로그인" : "회원가입"}</button></form>{message && <p className="mt-4 rounded-lg bg-[#fff3ee] p-3 text-xs leading-5 text-[#c45c43]">{message}</p>}<button onClick={() => { setMode(mode === "login" ? "signup" : "login"); setMessage(""); }} className="mt-5 w-full text-xs text-[#777570] underline underline-offset-4">{mode === "login" ? "처음 사용하시나요? 회원가입" : "이미 계정이 있나요? 로그인"}</button></section></main>;
}

function Navigation({ view, onChange }: { view: View; onChange: (view: View) => void }) { return <nav className="flex gap-1 overflow-x-auto md:grid md:gap-2"><button onClick={() => onChange("today")} className={`flex shrink-0 items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${view === "today" ? "bg-[#f0ebe5] font-bold" : "text-[#777570]"}`}><Pencil className="h-4 w-4" /> 오늘의 기록</button><button onClick={() => onChange("calendar")} className={`flex shrink-0 items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${view === "calendar" ? "bg-[#f0ebe5] font-bold" : "text-[#777570]"}`}><CalendarDays className="h-4 w-4" /> 날짜별 보기</button><button onClick={() => onChange("todos")} className={`flex shrink-0 items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${view === "todos" ? "bg-[#f0ebe5] font-bold" : "text-[#777570]"}`}><ClipboardList className="h-4 w-4" /> 할 일 모아보기</button></nav>; }

function TodayView({ entries, selectedDate, filtered, category, setCategory, changeDate, toggleTodo, changeCategory, notify }: { entries: Entry[]; selectedDate: string; filtered: Entry[]; category: "all" | Category; setCategory: (category: "all" | Category) => void; changeDate: (amount: number) => void; toggleTodo: (id: Entry["id"]) => void; changeCategory: (id: Entry["id"], category: Category) => void; notify: (message: string) => void }) {
  const dayEntries = filtered.filter(item => item.date === selectedDate).sort((a, b) => a.time.localeCompare(b.time)); const dayCount = entries.filter(item => item.date === selectedDate).length; const todos = entries.filter(item => item.date === selectedDate && item.category === "todo").length;
  return <><section className="mb-8 grid gap-4 rounded-xl bg-[#2c2c2b] p-5 text-white sm:grid-cols-[1fr_auto]"><div><h2 className="mb-2 text-sm">{formatDate(selectedDate)} 기록 요약</h2><p className="m-0 text-xs leading-6 text-[#b9b7b1]">{dayCount ? `오늘은 ${dayCount}개의 기록을 남겼어요. ${Object.entries(categories).filter(([key]) => entries.some(item => item.date === selectedDate && item.category === key)).map(([key, value]) => value.label).join(", ")}가 담겨 있어요.` : "아직 남겨진 기록이 없어요."}</p></div><div className="flex items-center justify-around gap-5 sm:justify-end"><div className="text-center"><strong className="block text-2xl">{dayCount}</strong><span className="text-[10px] text-[#aaa]">전체 기록</span></div><div className="text-center"><strong className="block text-2xl">{todos}</strong><span className="text-[10px] text-[#aaa]">할 일</span></div></div></section><div className="mb-4 flex items-end justify-between"><div><h2 className="m-0 text-lg font-bold">오늘의 타임라인</h2><p className="mt-1 text-xs text-[#aaa]">작성한 순서대로 차곡차곡</p></div><div className="flex items-center gap-2 text-xs font-semibold text-[#827f79]"><button onClick={() => changeDate(-1)}><ChevronLeft className="h-4 w-4" /></button><span>{formatDate(selectedDate)}</span><button onClick={() => changeDate(1)}><ChevronRight className="h-4 w-4" /></button></div></div><div className="mb-5 flex flex-wrap gap-2"><button onClick={() => setCategory("all")} className={`rounded-full border px-3 py-1.5 text-[11px] ${category === "all" ? "border-[#252525] bg-[#252525] text-white" : "border-[#e9e7e1] bg-white text-[#8a8882]"}`}>전체</button>{Object.entries(categories).map(([key, value]) => <button key={key} onClick={() => setCategory(key as Category)} className={`rounded-full border px-3 py-1.5 text-[11px] ${category === key ? "border-[#252525] bg-[#252525] text-white" : "border-[#e9e7e1] bg-white text-[#8a8882]"}`}>{value.label}</button>)}</div><div className="relative pl-7 before:absolute before:bottom-1 before:left-2 before:top-1 before:border-l before:border-dashed before:border-[#dcd8d0]">{dayEntries.length ? dayEntries.map(item => <EntryCard key={item.id} item={item} toggleTodo={toggleTodo} changeCategory={changeCategory} notify={notify} />) : <Empty text="이 조건에 맞는 기록이 없어요." />}</div></>;
}

function EntryCard({ item, toggleTodo, changeCategory, notify }: { item: Entry; toggleTodo: (id: Entry["id"]) => void; changeCategory: (id: Entry["id"], category: Category) => void; notify: (message: string) => void }) { const meta = categories[item.category]; return <article className="relative mb-3 rounded-xl border border-[#e9e7e1] bg-white p-4 shadow-[0_4px_15px_rgba(62,47,32,0.03)] before:absolute before:-left-[27px] before:top-6 before:h-2.5 before:w-2.5 before:rounded-full before:border-2 before:border-[#f8f7f3] before:bg-[#ef754f]"><div className="mb-2 flex items-center justify-between"><span className={`rounded px-2 py-1 text-[10px] font-bold ${meta.color}`}>{meta.label}</span><span className="font-mono text-[11px] text-[#aaa]">{item.time}</span></div><p className="m-0 text-sm leading-7">{escapeText(item.text)}</p><div className="mt-2 flex justify-between text-[11px] text-[#aaa]"><span>{formatDate(item.date)}</span><div className="flex gap-3"><button onClick={() => { const next = window.prompt("카테고리: 업무 / 일기 / 감정 / 할 일 / 아이디어 / 기타", meta.label); const match = Object.entries(categories).find(([, value]) => value.label === next)?.[0] as Category | undefined; if (match) { changeCategory(item.id, match); notify("카테고리를 수정했어요."); } }}>{item.category === "todo" ? "카테고리 수정" : "분류 수정"}</button>{item.category === "todo" && <button onClick={() => toggleTodo(item.id)}>{item.done ? "완료됨" : "완료 처리"}</button>}</div></div></article>; }

function CalendarView({ entries, selectedDate, onSelect }: { entries: Entry[]; selectedDate: string; onSelect: (date: string) => void }) { const selected = new Date(`${selectedDate}T00:00:00`); const year = selected.getFullYear(); const month = selected.getMonth(); const monthLabel = new Intl.DateTimeFormat("ko-KR", { year: "numeric", month: "long" }).format(selected); const firstDay = new Date(year, month, 1).getDay(); const daysInMonth = new Date(year, month + 1, 0).getDate(); return <><div className="mb-4"><h2 className="m-0 text-lg font-bold">기록 달력</h2><p className="mt-1 text-xs text-[#aaa]">{monthLabel} · 날짜를 누르면 그날의 타임라인으로 이동해요.</p></div><div className="rounded-xl border border-[#e9e7e1] bg-white p-3 sm:p-6"><div className="grid grid-cols-7 gap-1.5 text-center text-[10px] font-semibold text-[#aaa]"><span>일</span><span>월</span><span>화</span><span>수</span><span>목</span><span>금</span><span>토</span>{Array.from({ length: firstDay }).map((_, index) => <span key={`blank-${index}`} />)}{Array.from({ length: daysInMonth }, (_, index) => { const date = `${year}-${String(month + 1).padStart(2, "0")}-${String(index + 1).padStart(2, "0")}`; const has = entries.filter(item => item.date === date); return <button key={date} onClick={() => onSelect(date)} className={`min-h-14 rounded-lg border p-2 text-left font-mono text-xs ${date === selectedDate ? "border-[#f6c3b3] bg-[#fff2ed] text-[#ef754f]" : "border-[#f0eee9]"}`}><span>{index + 1}</span>{has.length > 0 && <span className="mt-3 flex gap-1">{has.slice(0, 3).map(item => <i key={item.id} className={`h-1.5 w-1.5 rounded-full ${categories[item.category].dot}`} />)}</span>}</button>; })}</div></div></>; }

function TodosView({ todos, range, setRange, toggleTodo }: { todos: Entry[]; range: "all" | "week" | "open"; setRange: (range: "all" | "week" | "open") => void; toggleTodo: (id: Entry["id"]) => void }) { const dates = Array.from(new Set(todos.map(item => item.date))).sort().reverse(); return <><div className="mb-4"><h2 className="m-0 text-lg font-bold">할 일 모아보기</h2><p className="mt-1 text-xs text-[#aaa]">날짜 범위와 검색어로 필요한 할 일만 찾아보세요.</p></div><div className="mb-6 flex gap-2"><button onClick={() => setRange("all")} className={`rounded-full border px-3 py-1.5 text-[11px] ${range === "all" ? "border-[#252525] bg-[#252525] text-white" : "border-[#e9e7e1] bg-white text-[#8a8882]"}`}>전체 기간</button><button onClick={() => setRange("week")} className={`rounded-full border px-3 py-1.5 text-[11px] ${range === "week" ? "border-[#252525] bg-[#252525] text-white" : "border-[#e9e7e1] bg-white text-[#8a8882]"}`}>최근 7일</button><button onClick={() => setRange("open")} className={`rounded-full border px-3 py-1.5 text-[11px] ${range === "open" ? "border-[#252525] bg-[#252525] text-white" : "border-[#e9e7e1] bg-white text-[#8a8882]"}`}>미완료만</button></div><div className="grid gap-4 md:grid-cols-2">{dates.length ? dates.map(date => <section key={date} className="rounded-xl border border-[#e9e7e1] bg-white p-5"><h3 className="mb-3 text-sm font-bold">{formatDate(date)}</h3>{todos.filter(item => item.date === date).map(item => <div key={item.id} className="flex gap-2.5 border-t border-[#f1efeb] py-2.5 text-sm"><button onClick={() => toggleTodo(item.id)} className={`grid h-[18px] w-[18px] shrink-0 place-items-center rounded border text-[11px] ${item.done ? "border-[#75b79a] bg-[#75b79a] text-white" : "border-[#d8d4cc]"}`}>{item.done && <Check className="h-3 w-3" />}</button><span className={item.done ? "text-[#aaa] line-through" : ""}>{item.text}</span></div>)}</section>) : <Empty text="조건에 맞는 할 일이 없어요." />}</div></>; }

function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-[#ddd8cf] bg-white p-11 text-center text-sm text-[#aaa]">{text}</div>; }
