"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import { getSupabaseBrowserClient } from "../lib/supabase";
import { useRecords } from "./records-provider";
import type { Medication, MedicationLog } from "../lib/types";

export type MedicationForm = { name: string; ingredient: string; doseAmount: string; doseUnit: string; schedule: string; instructions: string };
type MedicationChange = { id: string; changedAt: string; previousName: string; previousDoseAmount: string; previousDoseUnit: string; previousSchedule: string; nextName: string; nextDoseAmount: string; nextDoseUnit: string; nextSchedule: string };
type MedicationStore = { medications: Medication[]; logs: MedicationLog[]; changes: Record<string, MedicationChange[]>; loading: boolean; addMedication: (form: MedicationForm) => Promise<boolean>; updateMedication: (medication: Medication, form: MedicationForm) => Promise<boolean>; deleteMedication: (medication: Medication) => Promise<boolean>; logMedication: (medication: Medication, amount: string, unit: string, timing: string, note: string) => Promise<boolean>; uploadDocument: (medication: Medication, file: File) => Promise<boolean> };
const Ctx = createContext<MedicationStore | null>(null); const client = getSupabaseBrowserClient();
const medicationFromRow = (row: any): Medication => ({ id: row.id, name: row.name, ingredient: row.ingredient, doseAmount: row.dose_amount, doseUnit: row.dose_unit, schedule: row.schedule, instructions: row.instructions, active: row.active, createdAt: row.created_at, documentPath: row.document_path });
const logFromRow = (row: any): MedicationLog => ({ id: row.id, medicationId: row.medication_id, takenAt: row.taken_at, amount: row.amount, unit: row.unit, timing: row.timing, note: row.note });
const changeFromRow = (row: any): MedicationChange => ({ id: row.id, changedAt: row.changed_at, previousName: row.previous_name, previousDoseAmount: row.previous_dose_amount, previousDoseUnit: row.previous_dose_unit, previousSchedule: row.previous_schedule, nextName: row.next_name, nextDoseAmount: row.next_dose_amount, nextDoseUnit: row.next_dose_unit, nextSchedule: row.next_schedule });

export function MedicationProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const needsMedicationData = pathname === "/medications" || pathname === "/calendar"; const { session } = useRecords(); const [medications, setMedications] = useState<Medication[]>([]); const [logs, setLogs] = useState<MedicationLog[]>([]); const [changes, setChanges] = useState<Record<string, MedicationChange[]>>({}); const [loading, setLoading] = useState(Boolean(session && needsMedicationData));
  const load = async (userId: string) => { if (!needsMedicationData) { setMedications([]); setLogs([]); setChanges({}); setLoading(false); return; } if (!client) { const saved = localStorage.getItem("memento-medications"); const savedLogs = localStorage.getItem("memento-medication-logs"); if (saved) setMedications(JSON.parse(saved)); if (savedLogs) setLogs(JSON.parse(savedLogs)); setLoading(false); return; } const medsQuery = pathname === "/medications" ? client.from("medications").select("id, name, ingredient, dose_amount, dose_unit, schedule, instructions, active, document_path, created_at").eq("user_id", userId).order("active", { ascending: false }).order("created_at", { ascending: false }) : Promise.resolve({ data: [] as any[] }); const changesQuery = pathname === "/medications" ? client.from("medication_changes").select("id, medication_id, changed_at, previous_name, previous_dose_amount, previous_dose_unit, previous_schedule, next_name, next_dose_amount, next_dose_unit, next_schedule").eq("user_id", userId).order("changed_at", { ascending: false }) : Promise.resolve({ data: [] as any[] }); const [{ data: meds }, { data: logRows }, { data: changeRows }] = await Promise.all([medsQuery, client.from("medication_logs").select("id, medication_id, taken_at, amount, unit, timing, note").eq("user_id", userId).order("taken_at", { ascending: false }).limit(500), changesQuery]); const grouped: Record<string, MedicationChange[]> = {}; (changeRows ?? []).forEach((row: any) => { grouped[row.medication_id] = [...(grouped[row.medication_id] ?? []), changeFromRow(row)]; }); setMedications((meds ?? []).map(medicationFromRow)); setLogs((logRows ?? []).map(logFromRow)); setChanges(grouped); setLoading(false); };
  useEffect(() => { if (session) load(session.user.id); else { setMedications([]); setLogs([]); setChanges({}); setLoading(false); } }, [session, pathname]);
  useEffect(() => { if (!client) { localStorage.setItem("memento-medications", JSON.stringify(medications)); localStorage.setItem("memento-medication-logs", JSON.stringify(logs)); } }, [medications, logs]);
  const value = useMemo<MedicationStore>(() => ({ medications, logs, changes, loading,
    addMedication: async form => { if (client && session) { const { data, error } = await client.from("medications").insert({ user_id: session.user.id, name: form.name.trim(), ingredient: form.ingredient.trim() || null, dose_amount: form.doseAmount.trim(), dose_unit: form.doseUnit.trim(), schedule: form.schedule.trim(), instructions: form.instructions.trim() || null }).select("id, name, ingredient, dose_amount, dose_unit, schedule, instructions, active, document_path, created_at").single(); if (error || !data) return false; setMedications(items => [medicationFromRow(data), ...items]); return true; } setMedications(items => [{ id: `local-${Date.now()}`, name: form.name.trim(), ingredient: form.ingredient.trim() || null, doseAmount: form.doseAmount.trim(), doseUnit: form.doseUnit.trim(), schedule: form.schedule.trim(), instructions: form.instructions.trim() || null, active: true, createdAt: new Date().toISOString() }, ...items]); return true; },
    updateMedication: async (medication, form) => { const next = { ...medication, name: form.name.trim(), ingredient: form.ingredient.trim() || null, doseAmount: form.doseAmount.trim(), doseUnit: form.doseUnit.trim(), schedule: form.schedule.trim(), instructions: form.instructions.trim() || null }; setMedications(items => items.map(item => item.id === medication.id ? next : item)); if (client && session) { const { error } = await client.from("medications").update({ name: next.name, ingredient: next.ingredient, dose_amount: next.doseAmount, dose_unit: next.doseUnit, schedule: next.schedule, instructions: next.instructions }).eq("id", medication.id).eq("user_id", session.user.id); if (error) return false; await client.from("medication_changes").insert({ user_id: session.user.id, medication_id: medication.id, previous_name: medication.name, previous_dose_amount: medication.doseAmount, previous_dose_unit: medication.doseUnit, previous_schedule: medication.schedule, next_name: next.name, next_dose_amount: next.doseAmount, next_dose_unit: next.doseUnit, next_schedule: next.schedule }); } return true; },
    deleteMedication: async medication => { setMedications(items => items.filter(item => item.id !== medication.id)); setLogs(items => items.filter(item => item.medicationId !== medication.id)); if (client && session) { const { error } = await client.from("medications").delete().eq("id", medication.id).eq("user_id", session.user.id); if (error) return false; } return true; },
    logMedication: async (medication, amount, unit, timing, note) => { const takenAt = new Date().toISOString(); if (client && session) { const { data, error } = await client.from("medication_logs").insert({ user_id: session.user.id, medication_id: medication.id, taken_at: takenAt, amount, unit, timing, note: note.trim() || null }).select("id, medication_id, taken_at, amount, unit, timing, note").single(); if (error || !data) return false; setLogs(items => [logFromRow(data), ...items]); return true; } setLogs(items => [{ id: `local-log-${Date.now()}`, medicationId: medication.id, takenAt, amount, unit, timing, note: note.trim() || null }, ...items]); return true; },
    uploadDocument: async (medication, file) => { if (!client || !session) return false; const path = `${session.user.id}/${medication.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "_")}`; const { error } = await client.storage.from("medication-documents").upload(path, file, { upsert: false }); if (error) return false; const { error: updateError } = await client.from("medications").update({ document_path: path }).eq("id", medication.id).eq("user_id", session.user.id); if (updateError) return false; setMedications(items => items.map(item => item.id === medication.id ? { ...item, documentPath: path } : item)); return true; }
  }), [medications, logs, changes, loading, session]); return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export function useMedications() { const value = useContext(Ctx); if (!value) throw new Error("useMedications must be used within MedicationProvider"); return value; }
