"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";
import { usePathname } from "next/navigation";
import type { Session } from "@supabase/supabase-js";
import { getSupabaseBrowserClient, supabaseConfigured } from "../lib/supabase";
import { autoCategory, defaultCategories } from "../lib/categories";
import { localDate } from "../lib/date";
import { defaultReminderAt, effectiveTodoDate } from "../lib/todo";
import type { Category, CategoryOption, Entry, EntryRevision, TodoDetails } from "../lib/types";

type Store = { entries: Entry[]; session: Session | null; loading: boolean; configured: boolean; categories: CategoryOption[]; add: (text: string, category: Category | "auto") => Promise<boolean>; toggle: (entry: Entry) => Promise<void>; updateText: (entry: Entry, text: string) => Promise<boolean>; updateCategory: (entry: Entry, category: Category) => Promise<void>; updateTodoDetails: (entry: Entry, details: TodoDetails) => Promise<void>; deleteEntry: (entry: Entry) => Promise<boolean>; addCategory: (label: string) => Promise<void>; signOut: () => Promise<void> };
const Ctx = createContext<Store | null>(null); const client = getSupabaseBrowserClient();
const rowToRevision = (row: any): EntryRevision => ({ id: row.id, previousText: row.previous_text, nextText: row.next_text, changedAt: row.changed_at });
const rowToEntry = (row: any, history: EntryRevision[] = []): Entry => ({ id: row.id, date: row.entry_date, time: String(row.entry_time).slice(0, 5), text: row.text, category: row.category, done: row.done, priority: row.priority ?? "normal", dueDate: row.due_date ?? null, dueTime: row.due_time ? String(row.due_time).slice(0, 5) : null, reminderAt: row.reminder_at ?? null, reminderSentAt: row.reminder_sent_at ?? null, history });

export function RecordsProvider({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [entries, setEntries] = useState<Entry[]>([]); const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(supabaseConfigured); const [categories, setCategories] = useState(defaultCategories);
  const load = async (userId: string) => { if (!client) return; const includeHistory = pathname !== "/todos" && pathname !== "/settings"; const entriesQuery = client.from("entries").select("id, entry_date, entry_time, text, category, done, priority, due_date, due_time, reminder_at, reminder_sent_at").eq("user_id", userId).order("entry_date", { ascending: false }).order("entry_time", { ascending: false }); const revisionsQuery = includeHistory ? client.from("entry_revisions").select("id, entry_id, previous_text, next_text, changed_at").eq("user_id", userId).order("changed_at", { ascending: false }) : Promise.resolve({ data: [] as any[] }); const [{ data }, { data: revisions }] = await Promise.all([entriesQuery, revisionsQuery]); const historyByEntry = new Map<string, EntryRevision[]>(); (revisions ?? []).forEach((row: any) => { const list = historyByEntry.get(row.entry_id) ?? []; list.push(rowToRevision(row)); historyByEntry.set(row.entry_id, list); }); const today = localDate(); const mapped = (data ?? []).map((row: any) => rowToEntry(row, historyByEntry.get(row.id) ?? [])); const normalized = mapped.map(item => { if (item.category !== "todo" || item.done) return item; const dueDate = effectiveTodoDate(item, today); const needsReminder = !item.reminderAt || (item.dueDate !== dueDate && !item.reminderSentAt); const reminderAt = needsReminder ? defaultReminderAt(dueDate) : item.reminderAt; return { ...item, dueDate, reminderAt, reminderSentAt: needsReminder ? null : item.reminderSentAt }; }); setEntries(normalized); void Promise.all(normalized.filter((item, index) => { const original = mapped[index]; return item.category === "todo" && !item.done && (item.dueDate !== original.dueDate || item.reminderAt !== original.reminderAt); }).map(item => client.from("entries").update({ due_date: item.dueDate, reminder_at: item.reminderAt, reminder_sent_at: null }).eq("id", item.id).eq("user_id", userId))); };
  useEffect(() => { if (!client) { const saved = localStorage.getItem("memento-entries"); if (saved) setEntries(JSON.parse(saved)); return; } let active = true; client.auth.getSession().then(({ data }) => { if (!active) return; setSession(data.session); setLoading(false); }); const { data } = client.auth.onAuthStateChange((_event, next) => { setSession(next); setLoading(false); if (!next) setEntries([]); }); return () => { active = false; data.subscription.unsubscribe(); }; }, []);
  useEffect(() => { if (session) { load(session.user.id); const custom = session.user.user_metadata?.categories; if (Array.isArray(custom)) setCategories([...defaultCategories, ...custom]); } }, [session, pathname]);
  useEffect(() => { if (!client) localStorage.setItem("memento-entries", JSON.stringify(entries)); }, [entries]);
  const value = useMemo<Store>(() => ({ entries, session, loading, configured: supabaseConfigured, categories,
    add: async (text, chosen) => { const category = chosen === "auto" ? autoCategory(text) : chosen; if (client && session) { const now = new Date(); const date = localDate(now); const { data, error } = await client.from("entries").insert({ user_id: session.user.id, entry_date: date, entry_time: now.toTimeString().slice(0, 5), text, category, done: false, priority: "normal", due_date: category === "todo" ? date : null, reminder_at: category === "todo" ? defaultReminderAt(date, now) : null, reminder_sent_at: null }).select("id, entry_date, entry_time, text, category, done, priority, due_date, due_time, reminder_at, reminder_sent_at").single(); if (error || !data) return false; setEntries(items => [rowToEntry(data), ...items]); return true; } const date = localDate(); setEntries(items => [{ id: String(Date.now()), date, time: new Date().toTimeString().slice(0, 5), text, category, done: false, priority: "normal", dueDate: category === "todo" ? date : null, dueTime: null, reminderAt: category === "todo" ? defaultReminderAt(date) : null, reminderSentAt: null, history: [] }, ...items]); return true; },
    toggle: async entry => { const done = !entry.done; setEntries(items => items.map(item => item.id === entry.id ? { ...item, done } : item)); if (client && session) await client.from("entries").update({ done }).eq("id", entry.id).eq("user_id", session.user.id); },
    updateText: async (entry, text) => { const nextText = text.trim(); if (!nextText || nextText === entry.text.trim()) return false; const changedAt = new Date().toISOString(); const revision: EntryRevision = { id: `revision-${Date.now()}`, previousText: entry.text, nextText, changedAt }; setEntries(items => items.map(item => item.id === entry.id ? { ...item, text: nextText, history: [revision, ...(item.history ?? [])] } : item)); if (client && session) { const { error } = await client.from("entries").update({ text: nextText }).eq("id", entry.id).eq("user_id", session.user.id); if (error) return false; await client.from("entry_revisions").insert({ entry_id: entry.id, user_id: session.user.id, previous_text: entry.text, next_text: nextText, changed_at: changedAt }); } return true; },
    updateCategory: async (entry, category) => { setEntries(items => items.map(item => item.id === entry.id ? { ...item, category } : item)); if (client && session) await client.from("entries").update({ category }).eq("id", entry.id).eq("user_id", session.user.id); },
    updateTodoDetails: async (entry, details) => { const dueDate = details.dueDate ?? effectiveTodoDate({ ...entry, ...details }, localDate()); const reminderAt = details.reminderAt ?? defaultReminderAt(dueDate); const normalized = { ...details, dueDate, reminderAt }; setEntries(items => items.map(item => item.id === entry.id ? { ...item, ...normalized, reminderSentAt: null } : item)); if (client && session) await client.from("entries").update({ priority: normalized.priority, due_date: normalized.dueDate, due_time: normalized.dueTime, reminder_at: normalized.reminderAt, reminder_sent_at: null }).eq("id", entry.id).eq("user_id", session.user.id); },
    deleteEntry: async entry => { setEntries(items => items.filter(item => item.id !== entry.id)); if (client && session) { const { error } = await client.from("entries").delete().eq("id", entry.id).eq("user_id", session.user.id); if (error) { setEntries(items => [entry, ...items]); return false; } } return true; },
    addCategory: async label => { const next = { key: `custom-${Date.now()}`, label, color: "bg-stone-soft text-stone-ink", dot: "bg-stone-ink" }; const custom = categories.filter(item => !defaultCategories.some(base => base.key === item.key)); setCategories(items => [...items, next]); if (client && session) await client.auth.updateUser({ data: { categories: [...custom, next] } }); },
    signOut: async () => { if (client) await client.auth.signOut(); }
  }), [entries, session, loading, categories]); return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export function useRecords() { const value = useContext(Ctx); if (!value) throw new Error("useRecords must be used within RecordsProvider"); return value; }
