"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";
import type { Session } from "@supabase/supabase-js";
import { getSupabaseBrowserClient, supabaseConfigured } from "../lib/supabase";
import { autoCategory, defaultCategories } from "../lib/categories";
import { localDate } from "../lib/date";
import type { Category, CategoryOption, Entry } from "../lib/types";

type Store = { entries: Entry[]; session: Session | null; loading: boolean; configured: boolean; categories: CategoryOption[]; add: (text: string, category: Category | "auto") => Promise<boolean>; toggle: (entry: Entry) => Promise<void>; updateCategory: (entry: Entry, category: Category) => Promise<void>; addCategory: (label: string) => Promise<void>; signOut: () => Promise<void> };
const Ctx = createContext<Store | null>(null); const client = getSupabaseBrowserClient();
const rowToEntry = (row: any): Entry => ({ id: row.id, date: row.entry_date, time: String(row.entry_time).slice(0, 5), text: row.text, category: row.category, done: row.done });
export function RecordsProvider({ children }: { children: React.ReactNode }) { const [entries, setEntries] = useState<Entry[]>([]); const [session, setSession] = useState<Session | null>(null); const [loading, setLoading] = useState(supabaseConfigured); const [categories, setCategories] = useState(defaultCategories);
  const load = async (userId: string) => { if (!client) return; const { data } = await client.from("entries").select("id, entry_date, entry_time, text, category, done").eq("user_id", userId).order("entry_date", { ascending: false }).order("entry_time", { ascending: false }); setEntries((data ?? []).map(rowToEntry)); };
  useEffect(() => { if (!client) { const saved = localStorage.getItem("memento-entries"); if (saved) setEntries(JSON.parse(saved)); return; } let active = true; client.auth.getSession().then(({ data }) => { if (!active) return; setSession(data.session); setLoading(false); }); const { data } = client.auth.onAuthStateChange((_event, next) => { setSession(next); setLoading(false); if (next) load(next.user.id); else setEntries([]); }); return () => { active = false; data.subscription.unsubscribe(); }; }, []);
  useEffect(() => { if (session) { load(session.user.id); const custom = session.user.user_metadata?.categories; if (Array.isArray(custom)) setCategories([...defaultCategories, ...custom]); } }, [session]);
  useEffect(() => { if (!client) localStorage.setItem("memento-entries", JSON.stringify(entries)); }, [entries]);
  const value = useMemo<Store>(() => ({ entries, session, loading, configured: supabaseConfigured, categories, add: async (text, chosen) => { const category = chosen === "auto" ? autoCategory(text) : chosen; if (client && session) { const now = new Date(); const { data, error } = await client.from("entries").insert({ user_id: session.user.id, entry_date: localDate(now), entry_time: now.toTimeString().slice(0, 5), text, category, done: false }).select("id, entry_date, entry_time, text, category, done").single(); if (error || !data) return false; setEntries(items => [rowToEntry(data), ...items]); return true; } setEntries(items => [{ id: String(Date.now()), date: localDate(), time: new Date().toTimeString().slice(0, 5), text, category, done: false }, ...items]); return true; }, toggle: async entry => { const done = !entry.done; setEntries(items => items.map(item => item.id === entry.id ? { ...item, done } : item)); if (client && session) await client.from("entries").update({ done }).eq("id", entry.id).eq("user_id", session.user.id); }, updateCategory: async (entry, category) => { setEntries(items => items.map(item => item.id === entry.id ? { ...item, category } : item)); if (client && session) await client.from("entries").update({ category }).eq("id", entry.id).eq("user_id", session.user.id); }, addCategory: async label => { const next = { key: `custom-${Date.now()}`, label, color: "bg-stone-soft text-stone-ink", dot: "bg-stone-ink" }; const custom = categories.filter(item => !defaultCategories.some(base => base.key === item.key)); setCategories(items => [...items, next]); if (client && session) await client.auth.updateUser({ data: { categories: [...custom, next] } }); }, signOut: async () => { if (client) await client.auth.signOut(); } }), [entries, session, loading, categories]); return <Ctx.Provider value={value}>{children}</Ctx.Provider>; }
export function useRecords() { const value = useContext(Ctx); if (!value) throw new Error("useRecords must be used within RecordsProvider"); return value; }
