"use client";

import { useEffect, useMemo, useState } from "react";
import { Bell, Check, Square } from "lucide-react";
import { Header } from "../../../components/record-widgets"; import { subscribeToPush } from "../../../lib/push";
import { useRecords } from "../../../components/records-provider";
import { formatKoreanDate, localDate } from "../../../lib/date";
import { effectiveTodoDate } from "../../../lib/todo";
import type { Entry, TodoDetails, TodoPriority } from "../../../lib/types";

const priorityLabels: Record<TodoPriority, string> = { low: "여유", normal: "보통", high: "중요", urgent: "긴급" };
function inputDateTime(value: string | null | undefined) { if (!value) return ""; const date = new Date(value); const pad = (item: number) => String(item).padStart(2, "0"); return `${date.getFullYear()}-${pad(date.getMonth() + 1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`; }
function isoDateTime(value: string) { return value ? new Date(value).toISOString() : null; }

function TodoItem({ entry }: { entry: Entry }) {
  const { toggle, updateTodoDetails } = useRecords();
  const [open, setOpen] = useState(false);
  const [details, setDetails] = useState<TodoDetails>({ priority: entry.priority ?? "normal", dueDate: entry.dueDate ?? null, dueTime: entry.dueTime ?? null, reminderAt: entry.reminderAt ?? null });
  const save = () => { updateTodoDetails(entry, details); setOpen(false); };
  return <div className="border-t border-[#f1efeb] py-3"><div className="flex items-start gap-2.5 text-sm"><button onClick={() => toggle(entry)} aria-label={entry.done ? "완료 취소" : "할 일 완료 처리"} className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-md border ${entry.done ? "border-green-ink bg-green-ink text-white" : "border-[#d8d4cc] bg-white text-muted"}`}>{entry.done ? <Check className="h-3.5 w-3.5" /> : <Square className="h-3.5 w-3.5 opacity-0" />}</button><div className="min-w-0 flex-1"><p className={`m-0 leading-6 ${entry.done ? "text-muted line-through" : ""}`}>{entry.text}</p><div className="mt-1 flex flex-wrap gap-2 text-[10px] text-muted">{entry.priority && entry.priority !== "normal" && <span className={entry.priority === "urgent" ? "font-bold text-coral-ink" : ""}>{priorityLabels[entry.priority]}</span>}{entry.dueDate && <span>마감 {entry.dueDate}{entry.dueTime ? ` ${entry.dueTime}` : ""}</span>}{entry.reminderAt && <span>🔔 {new Date(entry.reminderAt).toLocaleString("ko-KR", { month: "numeric", day: "numeric", hour: "numeric", minute: "2-digit" })}</span>}</div></div><button onClick={() => setOpen(value => !value)} className="rounded-md px-2 py-1 text-[11px] text-muted underline underline-offset-2">세부 설정</button></div>{open && <div className="mt-3 grid gap-3 rounded-lg bg-canvas p-3 sm:grid-cols-2"><label className="grid gap-1 text-[11px] text-muted">중요도<select value={details.priority} onChange={event => setDetails({ ...details, priority: event.target.value as TodoPriority })} className="rounded border border-line bg-white px-2 py-2 text-xs text-ink"><option value="low">여유</option><option value="normal">보통</option><option value="high">중요</option><option value="urgent">긴급</option></select></label><label className="grid gap-1 text-[11px] text-muted">마감 날짜<input type="date" value={details.dueDate ?? ""} onChange={event => setDetails({ ...details, dueDate: event.target.value || null })} className="rounded border border-line bg-white px-2 py-2 text-xs text-ink" /></label><label className="grid gap-1 text-[11px] text-muted">마감 시간<input type="time" value={details.dueTime ?? ""} onChange={event => setDetails({ ...details, dueTime: event.target.value || null })} className="rounded border border-line bg-white px-2 py-2 text-xs text-ink" /></label><label className="grid gap-1 text-[11px] text-muted">알림 시각<input type="datetime-local" value={inputDateTime(details.reminderAt)} onChange={event => setDetails({ ...details, reminderAt: isoDateTime(event.target.value) })} className="rounded border border-line bg-white px-2 py-2 text-xs text-ink" /></label><div className="flex items-center justify-end gap-2 sm:col-span-2"><button onClick={() => setOpen(false)} className="rounded-lg border border-line px-3 py-1.5 text-xs text-muted">취소</button><button onClick={save} className="rounded-lg bg-coral px-3 py-1.5 text-xs font-bold text-white">저장</button></div></div>}</div>;
}

export default function TodosPage() {
  const { entries } = useRecords();
  const [range, setRange] = useState<"all" | "week" | "open">("all"); const [query, setQuery] = useState(""); const [notifications, setNotifications] = useState(typeof Notification !== "undefined" && Notification.permission === "granted");
  const todos = useMemo(() => { let list = entries.filter(item => item.category === "todo" && (!query || item.text.toLowerCase().includes(query.toLowerCase()))); if (range === "open") list = list.filter(item => !item.done); if (range === "week") { const d = new Date(); d.setDate(d.getDate() - 6); const from = localDate(d); list = list.filter(item => effectiveTodoDate(item) >= from); } return list; }, [entries, range, query]);
  useEffect(() => { const check = () => { if (typeof Notification === "undefined" || Notification.permission !== "granted") return; todos.filter(item => !item.done && item.reminderAt && new Date(item.reminderAt).getTime() <= Date.now()).forEach(item => { const key = `memento-reminder-${item.id}-${item.reminderAt}`; if (!sessionStorage.getItem(key)) { new Notification("memento 할 일 알림", { body: item.text }); sessionStorage.setItem(key, "sent"); } }); }; check(); const timer = window.setInterval(check, 30000); return () => window.clearInterval(timer); }, [todos]);
  const enableNotifications = async () => { try { await subscribeToPush(); setNotifications(true); } catch (error) { window.alert(error instanceof Error ? error.message : "알림 설정에 실패했습니다."); } };
  const grouped = useMemo(() => { const byDate = new Map<string, Entry[]>(); todos.forEach(item => { const date = effectiveTodoDate(item); byDate.set(date, [...(byDate.get(date) ?? []), item]); }); return [...byDate.entries()].sort(([a], [b]) => b.localeCompare(a)).map(([date, items]) => ({ date, items })); }, [todos]);
  return <><Header title="할 일 모아보기" onSearch={setQuery} /><div className="mb-5 flex flex-wrap items-center gap-2"><div className="flex gap-2">{[["all", "전체 기간"], ["week", "최근 7일"], ["open", "미완료만"]].map(([key, label]) => <button key={key} onClick={() => setRange(key as typeof range)} className={`rounded-full border px-3 py-1.5 text-[11px] ${range === key ? "border-ink bg-ink text-white" : "border-line bg-white text-muted"}`}>{label}</button>)}</div><button onClick={enableNotifications} className={`ml-auto flex items-center gap-1 rounded-full border px-3 py-1.5 text-[11px] ${notifications ? "border-green-ink bg-green-soft text-green-ink" : "border-line bg-white text-muted"}`}><Bell className="h-3.5 w-3.5" />{notifications ? "알림 허용됨" : "알림 켜기"}</button></div><div className="grid gap-4 md:grid-cols-2">{grouped.length ? grouped.map(({ date, items }) => <section key={date} className="rounded-xl border border-line bg-white p-5"><h2 className="mb-1 text-sm font-bold">{formatKoreanDate(date)}</h2><p className="mb-2 text-[10px] text-muted">할 일 {items.length}개</p>{items.map(item => <TodoItem key={item.id} entry={item} />)}</section>) : <div className="rounded-xl border border-dashed border-line bg-white p-10 text-center text-sm text-muted">조건에 맞는 할 일이 없어요.</div>}</div></>;
}
